### ISSUE TITLE
Closed source games/projects listed under open source

### ISSUE THREAD

**Issue by godofgrunts** [uraimo/awesome-software-patreons#13]
CEMU - [closed source.](https://en.wikipedia.org/wiki/Cemu)
Dwarf Fortress - Source won't be released [until Toady dies](https://www.pcgamesn.com/dwarf-fortress/dwarf-fortress-source-code)
Sol Prime - as far as I can tell, is not open source.
Dark Flame - doesn't appear to be open source.
Launchbox - also doesn't appear to be open source.

**Comment by uraimo** [comment]
Fixed, I may bring them back in a specific "Freeware" category one day, we'll see.
